#!/bin/bash
# Instructions for pushing to GitHub

echo "🚀 Ready to push to GitHub!"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣  Create a repository on GitHub:"
echo "   👉 Go to: https://github.com/new"
echo "   - Repository name: selfhub-pitch-deck (or your choice)"
echo "   - Make it PUBLIC (required for free GitHub Pages)"
echo "   - Don't check any boxes (no README, .gitignore, license)"
echo "   - Click 'Create repository'"
echo ""
echo "2️⃣  After creating the repo, GitHub will show you commands."
echo "   Run these commands (replace YOUR_USERNAME and YOUR_REPO_NAME):"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Enable GitHub Pages:"
echo "   - Go to your repository on GitHub"
echo "   - Click 'Settings' → 'Pages'"
echo "   - Source: 'Deploy from a branch'"
echo "   - Branch: 'main'"
echo "   - Folder: '/' (root)"
echo "   - Click 'Save'"
echo ""
echo "4️⃣  Your pitch deck will be live at:"
echo "   https://YOUR_USERNAME.github.io/YOUR_REPO_NAME/"
echo ""
echo "✨ It may take 1-2 minutes to go live!"
